# Generated by Django 4.1.6 on 2023-03-25 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('facility_name', models.CharField(max_length=200)),
                ('city_or_town', models.CharField(max_length=200)),
                ('region_of_location', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=100)),
                ('digital_address', models.CharField(max_length=100)),
                ('is_a_delivery', models.BooleanField(default=False)),
                ('telephone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_a_laboratory', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('region_of_location', models.CharField(max_length=200)),
                ('digital_address', models.CharField(max_length=100)),
            ],
        ),
    ]
