# Generated by Django 4.1.6 on 2023-03-14 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('Tel', models.IntegerField()),
                ('digital_address', models.CharField(max_length=100)),
                ('region_of_location', models.CharField(choices=[('UW', 'Upper West'), ('VR', 'Volta'), ('NR', 'Northen'), ('AS', 'Ashanti'), ('GR', 'Greater Accra'), ('OR', 'Oti Region'), ('SR', 'Savannah'), ('UE', 'Upper East')], max_length=2)),
                ('hospital_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('Tel', models.CharField(max_length=20)),
                ('digital_address', models.CharField(max_length=100)),
                ('region_of_location', models.CharField(max_length=50)),
                ('services_rendering', models.CharField(max_length=500)),
                ('laboratory_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(verbose_name='DOB')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('diagnosis', models.CharField(max_length=300)),
                ('facility', models.CharField(max_length=500, verbose_name='clinic/dept')),
                ('patient_id', models.CharField(max_length=1000)),
                ('insuarance_type', models.CharField(max_length=200)),
                ('insuarance_number', models.CharField(max_length=200)),
                ('mobile_number', models.IntegerField()),
                ('financial_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LDMSApp.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_id', models.CharField(max_length=100)),
                ('upload_pdf', models.FileField(blank=True, null=True, upload_to='static/test_results')),
                ('sample_appearance_when_received', models.CharField(max_length=400)),
                ('sample_container', models.CharField(max_length=100)),
                ('parameter', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('comments', models.TextField()),
                ('send_by', models.CharField(max_length=30)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LDMSApp.laboratory')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LDMSApp.patient')),
                ('send_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LDMSApp.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='RequestTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=200)),
                ('type_of_test', models.TextField()),
                ('specimen_id', models.CharField(max_length=500)),
                ('speciment_type', models.CharField(max_length=200)),
                ('test_status', models.CharField(choices=[('T', 'Timed'), ('F', 'Fasting'), ('S', 'STAT')], max_length=2)),
                ('department', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('name_requestor', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('request_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LDMSApp.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialSummmaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.CharField(max_length=50)),
                ('total_fee_due', models.CharField(max_length=50)),
                ('balance', models.CharField(max_length=50)),
                ('total_test', models.CharField(default=1, max_length=50, verbose_name='Total #test')),
                ('total_cost', models.CharField(max_length=50)),
                ('total_discount', models.CharField(max_length=50)),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('digital_address', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=15)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
