# Generated by Django 4.1.6 on 2023-03-04 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDMSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='time_issued',
            field=models.DateField(verbose_name=datetime.datetime(2023, 3, 4, 10, 5, 17, 854447, tzinfo=datetime.timezone.utc)),
        ),
    ]
