# Generated by Django 4.1.6 on 2023-03-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDMSApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesttest',
            old_name='test_to_run',
            new_name='type_of_test',
        ),
        migrations.AddField(
            model_name='requesttest',
            name='test_status',
            field=models.CharField(choices=[('T', 'Timed'), ('F', 'Fasting'), ('S', 'STAT')], default='T', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='sample_appearance_when_received',
            field=models.CharField(default='fresh', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testresult',
            name='sample_container',
            field=models.CharField(default='edta', max_length=100),
            preserve_default=False,
        ),
    ]
