# Generated by Django 4.1.6 on 2023-03-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LDMSApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='financial_summary',
            new_name='hospital',
        ),
        migrations.RemoveField(
            model_name='financialsummmaryrecord',
            name='payee',
        ),
    ]
