# Generated by Django 4.1.6 on 2023-03-09 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LDMSApp', '0002_rename_test_to_run_requesttest_type_of_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialsummmaryrecord',
            old_name='paid_amount',
            new_name='amount_paid',
        ),
        migrations.AlterField(
            model_name='financialsummmaryrecord',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
