# Generated by Django 4.1.6 on 2023-03-14 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDMSApp', '0003_patient_laboratory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='facility',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insuarance_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insuarance_type',
        ),
        migrations.AddField(
            model_name='patient',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LDMSApp.delivery'),
        ),
    ]
