# Generated by Django 4.1.6 on 2023-03-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDMSApp', '0004_hospital_hospital_head_laboratory_laboratory_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='Tel',
            field=models.CharField(max_length=20),
        ),
    ]
