# Generated by Django 4.1.6 on 2023-03-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDMSApp', '0005_alter_laboratory_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='laboratory_manager',
            field=models.CharField(default='tim', max_length=100),
            preserve_default=False,
        ),
    ]
