# Generated by Django 4.1.6 on 2023-03-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDMSApp', '0006_alter_laboratory_laboratory_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='region_of_location',
            field=models.CharField(max_length=50),
        ),
    ]
