# Generated by Django 4.1.6 on 2023-03-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LDMSApp', '0007_alter_laboratory_region_of_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttest',
            name='facility',
            field=models.CharField(default='tth', max_length=200),
            preserve_default=False,
        ),
    ]
